/**
 * Landing page — public home page with hero, features, how-it-works, and footer.
 *
 * Fully responsive with orange accent design system.
 */

import { Link } from "react-router-dom";
import Button from "../components/common/Button";

const FEATURES = [
  {
    title: "AI Workout Plans",
    description:
      "Get custom workout routines generated by AI based on your fitness level, available equipment, and goals.",
    icon: (
      <svg className="w-7 h-7 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h4v12H4zm12 0h4v12h-4zM2 10h2v4H2zm18 0h2v4h-2zM8 11h8v2H8z" />
      </svg>
    ),
    bg: "bg-primary/10",
  },
  {
    title: "Indian Diet Plans",
    description:
      "Enjoy culturally familiar meals — from poha to dal rice — perfectly portioned with macro breakdowns.",
    icon: (
      <svg className="w-7 h-7 text-success" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25" />
      </svg>
    ),
    bg: "bg-success/10",
  },
  {
    title: "Fully Personalized",
    description:
      "Every plan adapts to your body metrics, dietary preferences, budget, and available equipment.",
    icon: (
      <svg className="w-7 h-7 text-blue-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
      </svg>
    ),
    bg: "bg-blue-50",
  },
];

const STEPS = [
  {
    number: "01",
    title: "Create Your Profile",
    description: "Tell us about your body, goals, diet preferences, and available equipment.",
  },
  {
    number: "02",
    title: "AI Generates Your Plan",
    description: "Our AI creates a personalized 7-day workout and diet plan just for you.",
  },
  {
    number: "03",
    title: "Follow & Track Progress",
    description: "Follow your daily plan, swap meals you don't like, and regenerate anytime.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* ── Navbar ─────────────────────────────────────────── */}
      <header className="sticky top-0 z-30 bg-background/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-6xl mx-auto flex items-center justify-between px-6 py-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center">
              <svg className="w-6 h-6 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
              </svg>
            </div>
            <span className="text-xl font-bold text-text-main">FitPlan</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link to="/login">
              <Button variant="secondary">Log In</Button>
            </Link>
            <Link to="/register">
              <Button variant="primary">Get Started</Button>
            </Link>
          </div>
        </div>
      </header>

      {/* ── Hero ───────────────────────────────────────────── */}
      <section className="flex-1 flex items-center justify-center px-6 py-16 lg:py-24">
        <div className="max-w-3xl text-center">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary text-sm font-semibold px-4 py-2 rounded-full mb-6">
            <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
              <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
            </svg>
            AI-Powered Fitness
          </div>

          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-text-main leading-tight mb-6">
            Your Personal{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary to-orange-400">
              AI Fitness Coach
            </span>
          </h1>

          <p className="text-lg lg:text-xl text-text-muted mb-10 max-w-xl mx-auto leading-relaxed">
            Get personalized workout and Indian diet plans powered by AI,
            tailored to your goals and lifestyle.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link to="/register">
              <Button variant="primary" className="text-base px-8 py-4">
                Get Started Free →
              </Button>
            </Link>
            <Link to="/login">
              <Button variant="secondary" className="text-base px-8 py-4">
                Log In
              </Button>
            </Link>
          </div>

          {/* Feature pills */}
          <div className="flex flex-wrap justify-center gap-3 mt-12">
            {["Personalized Plans", "Indian Diet", "Meal Swapping", "No Equipment Needed"].map((f) => (
              <span
                key={f}
                className="bg-white shadow-card px-4 py-2 rounded-full text-sm text-text-muted font-medium hover:shadow-card-hover transition-shadow duration-300"
              >
                {f}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ───────────────────────────────────────── */}
      <section className="py-16 lg:py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold text-text-main mb-4">
              Everything You Need
            </h2>
            <p className="text-text-muted text-lg max-w-xl mx-auto">
              AI-crafted fitness plans designed specifically for the Indian lifestyle.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {FEATURES.map((feature) => (
              <div
                key={feature.title}
                className="bg-card rounded-card shadow-card p-8 hover:shadow-card-hover hover:-translate-y-1 transition-all duration-300"
              >
                <div className={`w-14 h-14 ${feature.bg} rounded-2xl flex items-center justify-center mb-5`}>
                  {feature.icon}
                </div>
                <h3 className="text-lg font-bold text-text-main mb-2">
                  {feature.title}
                </h3>
                <p className="text-sm text-text-muted leading-relaxed">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ───────────────────────────────────── */}
      <section className="py-16 lg:py-24 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl lg:text-4xl font-bold text-text-main mb-4">
              How It Works
            </h2>
            <p className="text-text-muted text-lg max-w-xl mx-auto">
              Three simple steps to your personalized fitness plan.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {STEPS.map((step, idx) => (
              <div key={step.number} className="text-center relative">
                {/* Connector line */}
                {idx < STEPS.length - 1 && (
                  <div className="hidden md:block absolute top-8 left-[60%] w-[80%] h-0.5 bg-border" />
                )}
                <div className="w-16 h-16 bg-primary/10 text-primary font-bold text-xl rounded-full flex items-center justify-center mx-auto mb-4 relative z-10">
                  {step.number}
                </div>
                <h3 className="text-lg font-bold text-text-main mb-2">
                  {step.title}
                </h3>
                <p className="text-sm text-text-muted leading-relaxed max-w-xs mx-auto">
                  {step.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Footer ─────────────────────────────────────────── */}
      <footer className="py-8 px-6 border-t border-border">
        <div className="max-w-6xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary flex items-center justify-center">
              <svg className="w-5 h-5 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M3.75 13.5l10.5-11.25L12 10.5h8.25L9.75 21.75 12 13.5H3.75z" />
              </svg>
            </div>
            <span className="font-bold text-text-main">FitPlan</span>
          </div>
          <p className="text-sm text-text-muted">
            © {new Date().getFullYear()} FitPlan. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
